include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Snapshot Manager
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base

PKG_NAME:=luci-app-snapshot
PKG_VERSION:=1.0
PKG_RELEASE:=1

include ../../luci.mk
